#pragma once

#include "System.h"
#include <Eigen/Core>
#include <Eigen/StdVector>
#include <opencv2/core/core.hpp>
#include <boost/property_tree/ptree.hpp>
#include <boost/property_tree/json_parser.hpp>
#include <boost/filesystem.hpp>
#include <boost/lexical_cast.hpp>
#include <boost/program_options.hpp>
#include <boost/optional.hpp>
#include <boost/range/iterator_range.hpp>
#include <boost/noncopyable.hpp>
#include <memory>
#include <chrono>
#include <string>
#include <vector>
#include <map>
#include <iostream>
#include <chrono>
#include <vector>
#include <iterator>
#include <iostream>
#include <atomic>
#include <condition_variable>
#include <thread>
#include <mutex>
#include <stdexcept>
#include <algorithm>
#include <queue>
